### ISSUE TITLE
vue-facing-decorator, vue-i18n can't load local i18n bloc

### ISSUE THREAD

**Issue by rdhainaut** [facing-dev/vue-facing-decorator#64]
I'm currently attempting to migrate a large Vue 2 application to Vue 3. As a result, I'm utilizing the vue-facing-decorator. I appreciate the creation of this library, as it prevents the migration from becoming a complete rewrite from scratch.

In my project, I have a dependency on vue-i18n and I use localized i18n custom blocks in components to add translations for each component. I've discovered a conflict between vue-facing-decorator and vue-i18n, where local messages are not being loaded.

I've identified the cause of this issue and have published a fix. However, I would value your opinion on this matter. It might assist someone else, considering I spent five days figuring out why it wasn't working as expected.

Note: This issue seems to occur only when I define the following alias: 'vue-facing-decorator': 'vue-facing-decorator/dist/index-return-cons'.

the issue: https://github.com/intlify/bundle-tools/issues/268
the fix: https://github.com/intlify/bundle-tools/pull/269

**Comment by rdhelms** [comment]
@rdhainaut Just out of curiosity, what effect does removing that alias have? We haven't actually been using that alias in our migration and haven't noticed any issues, but we also aren't using vue-i18n

**Comment by rdhainaut** [comment]
> @rdhainaut Just out of curiosity, what effect does removing that alias have? We haven't actually been using that alias in our migration and haven't noticed any issues, but we also aren't using vue-i18n

If you remove the alias then the i18n plugin works as expected (and so local messages stored in i18n component bloc are loaded) but then other feature are broken and the official doc of vue facing decorator recommend to add that alias (see: https://facing-dev.github.io/vue-facing-decorator/#/en/compatibility/reflect-metadata/reflect-metadata)

I have created a repo with the issue here https://github.com/rdhainaut/vue3-vfd-i18n-issue (and you can try the behavior in comment the line 18 of vite.config https://github.com/rdhainaut/vue3-vfd-i18n-issue/blob/master/vite.config.ts)

**Comment by ruojianll** [comment]
Try replace your patch with `Component.__o || Component.__vccOpts || Component` and see if it works.

Keep the alias enabled.

**Comment by rdhainaut** [comment]
> Try replace your patch with `Component.__o || Component.__vccOpts || Component` and see if it works.
> 
> Keep the alias enabled.

Done (and it works as expected if I add "Component.__vccOpts" only )
https://github.com/intlify/bundle-tools/pull/269/commits/767f2baba965ea558c47340786ed42827dfcad1d

**Comment by rdhelms** [comment]
@rdhainaut With the patch in your example repo (and the alias still present) the local translations seem to be working but I'm seeing warnings about not seeing the global "hello" key - is that expected?

<img width="492" alt="image" src="https://github.com/facing-dev/vue-facing-decorator/assets/7010586/51e11027-c03b-4844-a20d-2ed3880695c6">
<img width="650" alt="image" src="https://github.com/facing-dev/vue-facing-decorator/assets/7010586/a77c8385-3ec2-4ebe-87af-b38271e2f12e">

**Comment by rdhainaut** [comment]
> @rdhainaut With the patch in your example repo (and the alias still present) the local translations seem to be working but I'm seeing warnings about not seeing the global "hello" key - is that expected?
> 
> <img alt="image" width="492" src="https://user-images.githubusercontent.com/7010586/240917280-51e11027-c03b-4844-a20d-2ed3880695c6.png"> <img alt="image" width="650" src="https://user-images.githubusercontent.com/7010586/240917376-a77c8385-3ec2-4ebe-87af-b38271e2f12e.png">

Yes: it s the expected behaviour 
By default, vue-i18n print 2 warnings when the key doesn't exist in local messages and then fallback to global messages
It s the case here

Official doc: https://vue-i18n.intlify.dev/guide/essentials/local.html#i18n-component-options
![image](https://github.com/facing-dev/vue-facing-decorator/assets/19733832/78cc0bd3-6e9b-4332-8473-fef863843e01)
